name: Analysis

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  linter:
    runs-on: ubuntu-latest
    container:
      image: davevader/pymrm_linux:1.0
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: test flake 8
        run: |
          flake8 --output-file=test/linter_errors.txt ./src/
          flake8_junit test/linter_errors.txt test/linter_errors.xml


      - name: Archive Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linter
          path: test/linter_errors.*

  publish-analysis:
    # For details checkout https://github.com/marketplace/actions/publish-test-results
    runs-on: ubuntu-latest
    container:
      image: davevader/pymrm_linux:1.0
# workaround, potentially leave the user as root in dockerfile
# see here: https://github.com/actions/checkout/issues/956
      options: --user root

    name: Publish Tests Results
    needs: [linter]
    permissions:
      checks: write
      # only needed unless run with comment_mode: off
      pull-requests: write
      # only needed for private repository
      contents: read
      # only needed for private repository
      issues: read
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Analysis
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            artifacts/linter/*.xml
