name: Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  install_pip:
    runs-on: ubuntu-latest
    container:
      image: python:3.10

    steps:
    - uses: actions/checkout@v4

    - name: Test Install
      run: python -m pip install .
  install_conda:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3

    steps:
    - uses: actions/checkout@v4
    - name: add_forge
      run: conda config --add channels conda-forge
    - name: install_gcc
      run: conda install gcc
    - name: Test Install
      run: python -m pip install .
